#ifndef __ERRORS__
#define __ERRORS__

enum errors
{
	ERR_SUCCESS,
	ERR_OPEN_FILE,
	ERR_READING_FILE,
	ERR_INCORRECT_COMMAND,
	ERR_INCORRECT_COORDINATES,
	ERR_INCORRECT_OFFSET,
	ERR_INCORRECT_ANGLES,
	ERR_INCORRECT_CENTER,
};

#endif // __ERRORS__
